### ISSUE TITLE
Complex selectors in :not pseudoselector

### ISSUE THREAD

**Issue by dbuijs** [cantino/selectorgadget#21]
I'm not sure if this is a bug or a feature, but I'd love to know how SelectorGadget manages to allow complex selectors inside the `:not` pseudoselector.

For example, from this html:

      <h2 id="heading1'> This is Heading 1 </h2>
      <p> Some text in section1 </p>
      <p> Some more text in section 1 </p>
      <ul>
          <li> Some random list in Section 1 </li>
     </ul>
     <h2 id="heading2"> This is Heading 2 </h2>
     <p> Some text in section 2 </p>
     <p> Some more text in section 2 </p>

I can give SelectorGadget the following CSS:

    h2:contains("Heading 1") ~ *:not(h2:contains("Heading 2") ~ *)

And get all the nodes in between the 2 `h2` elements (with the second `h2` as well). My understanding of the CSS specification is that the `:not` pseudoselector shouldn't allow this, and when I try using this selector elsewhere, it won't work. 

When I try to get an Xpath for that selector, I get the following from SelectorGadget:

    //h2//1')//~//*//2')//~//*)

And this doesn't even look like valid Xpath. 

That said, I would really like to be able to select all the sibling nodes between any 2 arbitrary nodes. Is there a library or CSS specification that SelectorGadget uses to do this?

**Comment by cantino** [comment]
Since SelectorGadget is using jQuery, this is taking advantage of jQuery's selector engine.  The XPath generated is only going to be correct for selectors recommended by SelectorGadget itself.  If you paste in your own selector, all bets are off.  Does that make sense?

**Comment by dbuijs** [comment]
Yeah that makes sense. Figured out how to solve the problem with just XPath and `rvest`. See https://github.com/hadley/rvest/issues/105 for details.

Thanks!

**Comment by cantino** [comment]
Sounds good!
