### ISSUE TITLE
Question !

### ISSUE THREAD

**Issue by mikhoul** [cantino/selectorgadget#22]
I know the bookmarklet has been ported to Chrome so do you intend to port it to Firefox too ?

Best Regards ! :smile:

**Comment by cantino** [comment]
Hey @mikhoul, the bookmarklet should work fine in firefox and be identical to the Chrome extension.  Did you have any issues with it?

**Comment by mikhoul** [comment]
It work fine in Firefox but I was under the impression that the addon version had more features than the bookmarklet. 

Thanks for the Bookmarklet ! :smiley:

**Comment by cantino** [comment]
Please let me know if you have any issues with it :)
