### ISSUE TITLE
how to prevent clicks from bubbling

### ISSUE THREAD

**Issue by officert** [cantino/selectorgadget#24]
Hi, I was wondering how you guys are able to catch click events and prevent them from propagating? I'm trying to build a Chrome extension that has some similar function and I need to prevent any clicks events from my own event handler.

**Comment by cantino** [comment]
I honestly forget-- you can look at the code. I think we're either adding a global handler that returns `false`, or we're floating a hidden element above the page to absorb clicks.

**Comment by cantino** [comment]
Here you go: https://github.com/cantino/selectorgadget/blob/master/lib/js/core/core.js.coffee#L271

**Comment by officert** [comment]
Thanks! I was looking through the code and couldn't quite figure it out. I had seen that function and thought maybe that was the trick, but I've yet to come across that way of doing it so thought it might have had some other purpose. Thanks again! awesome tool!
