### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by heaven** [cantino/selectorgadget#35]
I've modified Coffee files in `lib/js/core` and started guard but nothing happens, files in `build/` were not updated.

**Comment by cantino** [comment]
Thanks @heaven. Haven't looked at this project in a while. Does https://github.com/cantino/selectorgadget/pull/37 fix it for you?

**Comment by heaven** [comment]
@cantino yes, it seems that worked. Big thank you!

**Comment by cantino** [comment]
Great!
